name: Deploy
on:
  push:
    branches:
      - main
jobs:
  # 这个工作流程有一个名为build-and-deploy的任务
  build-and-deploy:
    # 这个任务运行在ubuntu-latest的环境中
    runs-on: ubuntu-latest
    steps:
      # 这个步骤用来检出代码
      - name: Checkout
        uses: actions/checkout@v2
      # 这个步骤用来安装pnpm
      - name: Install pnpm
        run: curl -f https://get.pnpm.io/v6.js | node - add --global pnpm
      - name: Change work dir
        run: cd ./client
      # 这个步骤用来安装依赖
      - name: Install dependencies
        run: pnpm install
      # 这个步骤用来打包项目
      - name: Build
        run: pnpm run build
      # 这个步骤用来部署项目到github pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          # 这里需要设置您的github令牌，您可以在https://github.com/settings/tokens生成一个
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # 这里需要设置您的项目打包后的输出目录，一般是dist或build
          publish_dir: ./dist
